import Header from "@/app/components/common/Header";
import "./styles/globals.css";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Poppins } from "next/font/google";
import Footer from "./components/common/Footer";

export const inter = Inter({ subsets: ["latin"] });
export const monterrat = Montserrat({ subsets: ["latin"] });
export const popins = Poppins({ subsets: ["latin"],weight:['100','200','300','400','500','600','700','800','900']} );

 const metadata = {
  title: "Verbyo ",
  description: "Generated by create Ha_3er007",
};
// const myFont = localFont({ src: '../../public/montreal (1)/montreal/PPNeueMontreal-Medium.ttf',
// subsets: ["latin"],
   

// })
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monterrat.className}>{children}</body>
      {/* <Footer/> */}
    </html>
  );
}
